conference:
  name: 'Barcelona Perl & Friends 2018'
  date: 'Saturday 17 Nov 2018'
  url: 'http://friends.barcelona.pm/2018/'
  registration_open: true
  registration_url: 'https://goo.gl/forms/UYNZ8hna513bJekh1'
  call_for_papers_open: false
  call_for_papers_url: 'https://goo.gl/forms/n0oGOE0HuXd4aR4g1'
  talks_open: true
  schedule_open: false
  finished: false

venue:
  name: 'CAPSiDE offices'
  url: 'https://capside.com'
  map_url: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11973.793882743914!2d2.16937!3d41.386066!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x60a6240b19be359b!2sCAPSiDE!5e0!3m2!1sca!2ses!4v1473529872313'
  lunch_map_url: 'https://goo.gl/rECGRD'
  rooms:
    - name: '/lib'
    - name: '/bin'

events:

talks:
 - author: 'Javi Moreno'
   name: 'Cómo divertirte haciendo una buena charla técnica'
   slug: 'como-divertirte-haciendo-una-buena-charla-tecnica'
   description: >
     Dar charlas y cursos es una de las mejores maneras que tenemos de devolver a la comunidad lo que nos ha aportado y a la vez mejorar nuestros propios conocimientos sobre cualquier materia. Pero no se nace sabiendo (como bastantes meetups evidencian dolorosamente cada semana) así que si quieres ahorrarte algunos de los problemas por los que he pasado y mantener más fácilmente la atención de los asistentes te contaré los trucos y técnicas que conozco.
   icon: 'fa-microphone'
   duration: 50
   accepted: true
 - author: 'Oriol Arcas Abella'
   name: 'eBPF, the secret weapon of Linux'
   slug: 'ebpf-the-secret-weapon-of-linux'
   description: >
       What is the secret tool used in Facebook and Cloudflare to resist massive DDoS attacks, trace SQL queries in real time or diagnose slow file systems, using 100-line Python programs? Come and learn about the hottest topic in Linux networking right now.
   icon: 'fa-user-secret'
   duration: 20
   accepted: true
 - author: 'Diego Kuperman'
   name: 'Growing and refactoring our workforce'
   slug: 'growing-and-refactoring-our-workforce'
   description: >
        In soysuper.com our architecture is highly event oriented since day one. We implemented resque on Perl and nowadays it supports a huge load of workers and queues. Last year we implemented a new product. It has grown so big that our way of handling jobs has become the biggest of our problems. I will explain how we solved this bottleneck.
   icon: 'fa-shopping-cart'
   duration: 50
   accepted: true
 - author: 'Quim De la Cruz'
   name: 'Build a blockchain without fancy words'
   slug: 'build-a-blockchain-without-fancy-words'
   description: >
       Seguro que has oído hablar del blockchain alguna vez, una tecnología que promete dar una solución a muchos problemas que nos plantea la sociedad. A pesar de su potencial muy poca gente sabe como funciona un sistema blockchain. Y como vosotros sabréis no hay nada mejor para entender un problema que programarlo. En esta charla programaremos nuestro propio sistema blockchain, con sus algoritmos de encriptación, sus algoritmos de minado, etc.
   icon: 'fa-link'
   duration: 20
   accepted: true
 - author: 'Jordi Delgado'
   name: 'Les projeccions de Futamura'
   slug: 'les-projeccions-de-futamura'
   description: >
       Explicarem les conseqüències pràctiques de tenir un programa que especialitza altres programes a alguns dels seus paràmetres de manera eficient. L'existència d'aquest programa ve assegurada per un teorema dels anys 30, però trobar-ne un d'eficient no ha estat gens fàcil. La prova és que va fer falta esperar a finals dels 80 per trobar-ne un. Avui dia llenguatges com C o Scheme ja tenen programes que creen programes especialitzats eficients.
   icon: 'fa-calendar-check-o'
   duration: 50
   accepted: true
 - author: 'Xavier Noria'
   name: 'The Phoenix Boot Process'
   slug: 'the-phoenix-boot-process'
   description: >
        This talk covers how Erlang/OTP boots applications, and how does that apply to Phoenix, the web framework for Elixir. The talk is not a code walkthrough, we are going to understand the boot process and present it in a way that is intended to be didactic for end-users.
   icon: 'fa-bolt'
   duration: 50
   accepted: true
 - author: 'vti'
   name: 'CPAN Audit'
   slug: 'cpan-audit'
   description: >
        CPAN Audit is an open source tool developed to query CPAN modules for known security vulnerabilities. I will explain what it's for and how we can all improve it.
   icon: 'fa-eye'
   duration: 20
   accepted: true
 - author: 'Alexander Salas Bastidas'
   name: 'Teclib Contributors Guides'
   slug: 'teclib-contributors-guides'
   description: >
       Las Guías de Contribuidores de Teclib son una colección de recursos para personas, comunidades y empresas que quieren aprender como desplegar y contribuir a un proyecto de software libre. Las guías fueron creadas y mantenidas por Teclib, pero no son exclusivas de los productos Teclib. Nuestro objetivo es agregar buenas prácticas de comunidades.
   icon: 'fa-users'
   duration: 20
   accepted: true
 - author: 'Jose Luis Pérez'
   name: 'Fruit pi as a hacking toolkit'
   slug: 'fruit-pi-as-a-hacking-toolkit'
   description: >
      Como usar las (Raspberry, Orange, Banana) pi en tu entorno de tabajo.
   icon: 'fa-lemon-o'
   duration: 20
   accepted: true
 - author: 'Pablo Vigo'
   name: 'Projecte Linkat 2018'
   slug: 'projecte-linkat-2018'
   description: >
       Novetats i estat del projecte Linkat al 2018
   icon: 'fa-linux'
   duration: 20
   accepted: true
 - author: 'Jorge Dias'
   name: 'All your cluster are belong to us'
   slug: 'all-your-cluster-are-belong-to-us'
   description: >
       In this talk I’ll present how we manage our fleet of database clusters at Schibsted using immutable infrastructure and continuous delivery. We offer Kafka and Cassandra as a managed service for other teams at the company with over 50 clusters and how we manage it with a small team of 5 people.
   icon: 'fa-space-shuttle'
   duration: 20
   accepted: true
 - author: 'Andreas Finger'
   name: 'Tricks for a simple(r) micro-service architecture'
   slug: 'tricks-for-a-simpler-micro-service-architecture'
   description: >
       How to add new services or extract services out of a monolith, while avoiding complexity, tight coupling, domino effects, high latency and pain in general. This talk will explain the benefits of the RabbitMQ message broker and give valuable tips how to configure it. The slides will contain cute bunnies.
   icon: 'fa-cubes'
   duration: 20
   accepted: true
 - author: 'Manuel Rivero'
   name: 'Retrofitting a legacy SPA to use a functional architecture'
   slug: 'retrofitting-a-legacy-spa-to-use-a-functional-architecture'
   description: >
       The talk is about how we retrofitted a legacy Om SPA to use a functional architecture like re-frame's one, and open sourced as a result the re-om & reffectory frameworks.
   icon: 'fa-refresh'
   duration: 50
   accepted: true
 - author: 'Jose Luis Martínez'
   name: 'Performance through lightweight'
   slug: 'performance-through-lightweight'
   description: >
      La tecnología de contenedores se está utilizando en mucho ámbitos.
      Esta charla está enfocada a exponer recetas y técnicas para hacer que tus contenedores sean más ligeros.
   icon: 'fa-car'
   duration: 20
   accepted: true
 - author: 'Francesc Guasch'
   name: 'Ravada: Free Virtual Desktops Manager'
   slug: 'ravada-free-vdi'
   description: >
      Ravada is free Virtual Machines manager built in Perl.
      I will show its features, how it is built and explain some use cases.
   icon: 'fa-desktop'
   duration: 20
   accepted: true
 - author: 'Marc Egea i Sala'
   name: 'The (git) stories we tell ourselves'
   slug: 'the-git-stories-we-tell-ourselves'
   description: >
     Git is a powerful tool, but we are far from taking full advantage of it.

     We often see control versions systems only as a backup or checkpoints for
     our code, and it's hard to see how using them one way or another can
     impact our development.

     I will explain some techniques and strategies that help me write better
     and more maintainable code.
   icon: 'fa-code-fork'
   duration: 20
   accepted: true
